# Generated by Django 4.1.2 on 2024-03-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tournament',
            table='tournaments',
        ),
    ]
