# Generated by Django 4.1.2 on 2024-03-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='custom_user_group', through='myapp.MyAppUserGroups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='custom_user_permission', through='myapp.MyAppUserPermissions', to='auth.permission'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user2',
        ),
    ]
