services:
  django:
    build:
      context: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      # Add other Django environment variables here if needed
    restart: always

  react:
    build:
      context: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
